/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Zero Waste Asia Brand Colors
        zwa: {
          blue: {
            50: 'var(--zwa-blue-50)',
            100: 'var(--zwa-blue-100)',
            200: 'var(--zwa-blue-200)',
            300: 'var(--zwa-blue-300)',
            400: 'var(--zwa-blue-400)',
            500: 'var(--zwa-blue-500)',
            600: 'var(--zwa-blue-600)',
            700: 'var(--zwa-blue-700)',
            800: 'var(--zwa-blue-800)',
            900: 'var(--zwa-blue-900)',
            950: 'var(--zwa-blue-950)',
          },
          gold: {
            50: 'var(--zwa-gold-50)',
            100: 'var(--zwa-gold-100)',
            200: 'var(--zwa-gold-200)',
            300: 'var(--zwa-gold-300)',
            400: 'var(--zwa-gold-400)',
            500: 'var(--zwa-gold-500)',
            600: 'var(--zwa-gold-600)',
            700: 'var(--zwa-gold-700)',
            800: 'var(--zwa-gold-800)',
            900: 'var(--zwa-gold-900)',
            950: 'var(--zwa-gold-950)',
          },
        },
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
        },
        green: {
          500: 'var(--green-500)',
          600: 'var(--green-600)',
          700: 'var(--green-700)',
        },
        bg: 'var(--bg)',
        'bg-muted': 'var(--bg-muted)',
        'bg-card': 'var(--bg-card)',
        fg: 'var(--fg)',
        'fg-muted': 'var(--fg-muted)',
        border: 'var(--border)',
        'border-muted': 'var(--border-muted)',
        primary: 'var(--primary)',
        'primary-light': 'var(--primary-light)',
        'primary-dark': 'var(--primary-dark)',
        'primary-contrast': 'var(--primary-contrast)',
        secondary: 'var(--secondary)',
        'secondary-light': 'var(--secondary-light)',
        'secondary-dark': 'var(--secondary-dark)',
        'secondary-contrast': 'var(--secondary-contrast)',
        accent: 'var(--accent)',
        'accent-dark': 'var(--accent-dark)',
        'header-bg': 'var(--header-bg)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      spacing: {
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        normal: 'var(--transition-normal)',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
}

